workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    
    environment:
      xcode: latest
      cocoapods: default
      groups:
        - ios-dev
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
    
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*'
          include: true
        - pattern: '[0-9]*'
          include: true
      cancel_previous_builds: true
    
    scripts:
      - name: Set version from tag
        script: |
          # Extract version from tag (remove 'v' prefix)
          APP_VERSION=${CM_TAG#v}
          echo "Building version: $APP_VERSION"
          echo "APP_VERSION=$APP_VERSION" >> $CM_ENV
          
          # Extract version number for versionCode (e.g., 0.0.7 -> 7)
          VERSION_CODE=$(echo "$APP_VERSION" | grep -oE '[0-9]+' | tail -1)
          if [ -z "$VERSION_CODE" ]; then
            VERSION_CODE=1
          fi
          echo "Version code: $VERSION_CODE"
          
          # Update app.json with jq
          if command -v jq &> /dev/null; then
            jq --arg ver "$APP_VERSION" --argjson code "$VERSION_CODE" '
              .expo.version = $ver |
              .expo.android.versionCode = $code |
              .expo.ios.buildNumber = ($code | tostring)
            ' app.json > app.json.tmp && mv app.json.tmp app.json
            
            echo "Updated app.json:"
            cat app.json | jq '.expo | {version, android: {versionCode}, ios: {buildNumber}}'
          else
            echo "jq not found, using sed..."
            sed -i '' "s/\"version\": \"[^\"]*\"/\"version\": \"$APP_VERSION\"/" app.json
            sed -i '' "s/\"versionCode\": [0-9]*/\"versionCode\": $VERSION_CODE/" app.json
            sed -i '' "s/\"buildNumber\": \"[0-9]*\"/\"buildNumber\": \"$VERSION_CODE\"/" app.json
          fi

      - name: Install Bun
        script: |
          curl -fsSL https://bun.sh/install | bash
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"
          echo "BUN_INSTALL=$BUN_INSTALL" >> $CM_ENV
          echo "PATH=$BUN_INSTALL/bin:$PATH" >> $CM_ENV
          bun --version
          
      - name: Install dependencies
        script: |
          export PATH="$BUN_INSTALL/bin:$PATH"
          bun install
          
      - name: Install Expo CLI and EAS CLI
        script: |
          export PATH="$BUN_INSTALL/bin:$PATH"
          bun add -g expo-cli eas-cli
          
      - name: Run Expo Prebuild
        script: |
          export PATH="$BUN_INSTALL/bin:$PATH"
          bunx expo prebuild --platform ios --clean
          
      - name: Install CocoaPods
        script: |
          cd ios && pod install
          
      - name: Build unsigned iOS App
        script: |
          cd ios
          # Get the workspace and scheme names
          WORKSPACE=$(ls -d *.xcworkspace | head -1)
          SCHEME=$(echo $WORKSPACE | sed 's/.xcworkspace//')
          echo "Building $SCHEME from $WORKSPACE"
          
          xcodebuild -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -archivePath $CM_BUILD_DIR/build.xcarchive \
            archive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            AD_HOC_CODE_SIGNING_ALLOWED=YES
            
      - name: Create IPA
        script: |
          mkdir -p $CM_BUILD_DIR/Payload
          cp -r $CM_BUILD_DIR/build.xcarchive/Products/Applications/*.app $CM_BUILD_DIR/Payload/
          cd $CM_BUILD_DIR
          zip -r paperand-${APP_VERSION}.ipa Payload
          rm -rf Payload

    artifacts:
      - "*.ipa"
    
    publishing:
      email:
        recipients:
          - chiraitori.dev@gmail.com
        notify:
          success: true
          failure: true
